---
output:
  html_document: default
  pdf_document: default
---
-----
title: "Homework 2"
output: html_document
--------------------------
TIDYING UP DATA
--------------------------

```{r warning= FALSE, include= FALSE, message= FALSE}
#run tidyverse
library(tidyverse)
library(knitr)
```


```{r warning= FALSE, include= FALSE, message= FALSE}
#First need to upload the | seperated text file, and turn into a tibble
#import
gaz_raw<- read.delim("hw1.txt", header = TRUE, sep = "|", quote = "\"",
           dec = ".", fill = TRUE, comment.char = "", na.strings = "NA")
as_tibble(gaz_raw)
```


```{r warning= FALSE, include= FALSE, message= FALSE}
#select the columns i want and rename to match assignment
#column select and rename 

newgaz<-select(gaz_raw,
        'feature ID'                 = FEATURE_ID,
       ' feature name'               = FEATURE_NAME,
        'feature class'              = FEATURE_CLASS,
        'state alpha'                = STATE_ALPHA,
        'county name'                = COUNTY_NAME,
        'primary latitude(decimal)' = PRIM_LAT_DEC,
        'primary longitude(decimal)' = PRIM_LONG_DEC,
        'source latitude(decimal)'   = SOURCE_LAT_DEC,
        'source longitude(decimal)'  = SOURCE_LONG_DEC,
        'elevation in meters'        = ELEV_IN_M,
        'map name'                   = MAP_NAME,
        'date created'               = DATE_CREATED,
        'date edited'                = DATE_EDITED
)

```


```{r warning= FALSE, include= FALSE, message= FALSE}
#re-write the data types
#tranform data types and get data ready for analysis
gaz_tibble<-as.tibble(newgaz)
write_csv(gaz_tibble, "gaz_tibble.csv")
gaz_tibble<-read_csv("gaz_tibble.csv",
                      col_types = cols( 
                        'feature ID'                 =col_double(),
                        'feature name'               =col_character(),
                        'feature class'              =col_character(),
                        'country name'               =col_character(),
                        'primary latitude(decimal)'  =col_double(),
                        'primary longitude(decimal)' =col_double(),
                        'source latitutde(decimal)'  =col_double(),
                        'source longitude(decimal)'  =col_double(),
                        'elevation in meters'        =col_double(),
                        'map name'                   =col_character(),
                        'date created'               =col_date(),
                        'date endited'               =col_date()
                      )
)
gaz_tibble %>% 
  drop_na('primary latitude(decimal)','primary longitude(decimal)')

gaz_tibble<-gaz_tibble %>% filter(`state alpha`== "CA")

```
-------------

```{r include= FALSE}
library(DBI)
library(RSQLite)
library(dplyr)
gaz_tibble<-as.data.frame(gaz_tibble)
conn<- DBI::dbConnect(RSQLite::SQLite(), path= ":memory:")
copy_to(conn, gaz_tibble, "gaz",
        temporary = FALSE)
```

What is the most-frequently-occuring feature name?
```{r}
dbGetQuery(conn, "SELECT     (`feature name`), 
                  COUNT       (`feature name`) AS COUNT 
                  FROM       gaz 
                  GROUP BY   (`feature name`) 
                  ORDER BY   count 
                  DESC LIMIT 1
;") 

```
What is the least-frequently-occuring feature class?
```{r}
dbGetQuery(conn, "SELECT          (`feature class`),
                                  COUNT(`feature class`) AS count 
                  FROM gaz 
                  GROUP BY        (`feature class`) 
                  ORDER BY        count 
                  ASC             LIMIT 2
;")
```
---------------
What is the approximate center point of each county?

```{r warning= FALSE, include= FALSE, message= FALSE}
coordgaz<- select(gaz_tibble, "county name", "feature class" , "primary latitude(decimal)","primary longitude(decimal)") %>% group_by(`county name`) 

coordgaz<-filter(coordgaz, `primary latitude(decimal)` !=0 , `primary longitude(decimal)` !=0)

summarizegaz<-summarise(coordgaz,
    maxlat=max(`primary latitude(decimal)`, na.rm=TRUE),
    minlat=min(`primary latitude(decimal)`, na.rm=TRUE), 
    maxlong=max(`primary longitude(decimal)`, na.rm=TRUE),
    minlong=min(`primary longitude(decimal)`, na.rm=TRUE))

summarizegaz<-summarizegaz %>% 
mutate(centerlat=(maxlat+minlat)/2, 
      centerlong=(maxlong+minlong)/2
)
```

```{r warning= FALSE, include= FALSE, message= FALSE}
summarizegaz<-as.data.frame(summarizegaz)
copy_to(conn, summarizegaz, "Q3",
        temporary = FALSE)
```

```{r}

dbGetQuery(conn, "SELECT `county name`,
                          centerlat As Center_Latitude, 
                          centerlong AS Center_Longitude 
                 FROM Q3 
                 LIMIT 12
;")

```

---------------------
What are the fractions of the total number of features in each county that are natural? man-made?

```{r}

Q4<-dbGetQuery(conn, "SELECT `county name`,
                      CASE
                        WHEN `feature class`          

                      IN('Airport','Bridge','Building','Canal','Cemetery','Census','Church','Civil','Crossing','Dam','Harbor','Hospital','Locale','Military','Mine','Oilfield','Park','Pillar','Populated Place','Post Office','Reserve','Reservoir','School','Tower','Trail','Tunnel','Well')
                    
                    THEN 'man_made'
                    ELSE 'natural'
                    END AS 'feature class type'
                    FROM gaz
;")

Q4<-Q4 %>% group_by(`county name`, `feature class type`) %>% tally() 
Q4<-spread(Q4, key= `feature class type`, value= `n`)
Q4<- Q4 %>% mutate(total= man_made + natural,
fraction_man_made= man_made/total,
fraction_natural= natural/ total)
Q4 <- select(Q4,
             `county name`,
             ` fraction_man_made`,
             `fraction_natural`
             )

kable(Q4,col.names= c("County Name"," Man Made Features"," Natural Features"),caption= "Fraction of Man Made and Natural Features", align = 'c' )


```


