---
title: "Homework 3"
author: "Matt Gargiulo"
output:
  html_notebook: default
  html_document:
    df_print: paged
---

```{r echo=FALSE, message=FALSE}
library(tidyverse)
library(devtools)
library(testthat)
library(roxygen2)
```

```{r echo=FALSE, message=FALSE }
#make a tibble with fish, count and freqency
fish<-read.table("fish.txt", header = TRUE)
use_data(fish, pkg = 'package', overwrite=T) # sand the data in the data package
fisha<-fish
colnames(fisha)<-"species"
x<-sample(LETTERS[1:5], 300, replace = T) # add locations
x<-data.frame(x)
colnames(x)="location"
locations<-x$location
fisha<-mutate(fisha, "location"=locations)
fisha<-mutate(fisha, "count"=rep(1, n=300))
fisha<-fisha%>% group_by(species, location) %>% tally() # need to tally to get a count #
fisha<-spread(fisha, key= `location`, value= `n`)
table1<-fisha
table1_matrix<-as.matrix(table1[2:6]) # tibbles r shitty for R; move to matrix
rownames(table1_matrix)=c("cod","salmon","shark","steelhead","tuna") # change the names of columns
table1_matrix
```

```{r}
# make a matrix with fish and price
table2<-matrix(c(7.50,8,12,15,4), ncol=1)
rownames(table2)=c("cod","salmon","shark","steelhead","tuna")
colnames(table2)= "price"
table2
```

```{r}
freqandrev(table1_matrix,table2)
```


```{r}

growthrate(14.3,-0.497,0.1656,0.08588,-0.004266)

```

```{r}
test_file('~/Desktop/ESM262/Assignment3/package/test/growthrate_works.R')
test_file('~/Desktop/ESM262/Assignment3/package/test/freqandrev_works.R')
```

